version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/ervitis/go-blueprints

    environment:
      TEST_RESULTS: /tmp/test-results
      GOPATH: $HOME/.go_project
      PATH: $GOPATH/bin:$PATH
      BUILD_PATH: ${GOPATH}/src/github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}

    steps:
      - checkout

      - run: |
          mkdir -p ${TEST_RESULTS}
          go get -u github.com/golang/dep/cmd/dep
          dep ensure
          go get github.com/jstemmer/go-junit-report

      - run:
          name: Run unit tests

          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -v -race ./... | tee ${TEST_RESULTS}/go-test.out

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results